#DATES MUST BE SUNDAYS!!
STARTPULL = "03/01/2016"
ENDPULL = "05/01/2020"

DATA_FOLDER = "1Data/"
BINNED_FOLDER = "2Binned/"
STANDARDIZED_FOLDER = "3Standardized_Binned/"
LASSO_RESULTS_FOLDER = "4Lasso_Results"
WINDOW_LENGTH = 4
